import type { ComponentType, SVGProps } from 'react'
import {
  AlignLeft,
  ArrowDown,
  ArrowDownToBracket,
  ArrowRight,
  ArrowRightToBracket,
  ArrowUpRightFromSquare,
  ArrowsRepeat,
  Award,
  Ban,
  Barcode,
  Bars,
  Bell,
  Book,
  Building,
  Bullhorn,
  CalendarMonth,
  Chart,
  ChartLineUp,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  ClockArrow,
  Close,
  CloudArrowUp,
  Cog,
  CubesStacked,
  DesktopPc,
  Dollar,
  Edit,
  Envelope,
  ExclamationCircle,
  Eye,
  EyeSlash,
  File,
  FileImage,
  FileVideo,
  Filter,
  Fingerprint,
  FloppyDisk,
  Folder,
  FolderOpen,
  FolderPlus,
  Image,
  Layers,
  Lock,
  MapPin,
  MessageDots,
  Moon,
  OpenDoor,
  Palette,
  PaperClip,
  PaperPlane,
  Pen,
  Plus,
  ProfileCard,
  Refresh,
  Server,
  Shield,
  Sun,
  Tag,
  Tools,
  Tracking,
  TrashBin,
  Upload,
  User,
  Users,
  UsersGroup,
  VideoCamera,
  VolumeMute,
  VolumeUp,
} from 'flowbite-react-icons/outline'

import { cn } from '@/lib/utils'

type SvgIcon = ComponentType<SVGProps<SVGSVGElement> & { size?: string | number }>

/**
 * Catálogo central de Flowbite Icons.
 *
 * Los recursos declarativos usan nombres semánticos (`user`, `bell`, etc.) y el
 * componente los resuelve a SVG sin acoplar cada vista a una importación concreta.
 */
const icons: Record<string, SvgIcon> = {
  'align-left': AlignLeft,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'ban': Ban,
  'barcode': Barcode,
  'bars': Bars,
  'bell': Bell,
  'bell-slash': VolumeMute,
  'bolt': Tracking,
  'book': Book,
  'boxes-stacked': CubesStacked,
  'building': Building,
  'bullhorn': Bullhorn,
  'calendar': CalendarMonth,
  'chart-line': ChartLineUp,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-check': CheckCircle,
  'circle-exclamation': ExclamationCircle,
  'clock': Clock,
  'clock-rotate-left': ClockArrow,
  'cloud-arrow-down': ArrowDownToBracket,
  'cloud-upload-alt': CloudArrowUp,
  'cogs': Cog,
  'copyright': Award,
  'cubes': CubesStacked,
  'dollar-sign': Dollar,
  'envelope': Envelope,
  'exclamation-triangle': ExclamationCircle,
  'external-link-alt': ArrowUpRightFromSquare,
  'eye': Eye,
  'eye-slash': EyeSlash,
  'file': File,
  'filter-circle-xmark': Filter,
  'fingerprint': Fingerprint,
  'folder': Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'gauge-high': Chart,
  'image': Image,
  'layer-group': Layers,
  'list-check': ClipboardList,
  'location-dot': MapPin,
  'lock': Lock,
  'map-pin': MapPin,
  'message': MessageDots,
  'microchip': DesktopPc,
  'moon': Moon,
  'palette': Palette,
  'paperclip': PaperClip,
  'paper-plane': PaperPlane,
  'pen': Pen,
  'pen-to-square': Edit,
  'photo-film': FileImage,
  'photo-video': FileVideo,
  'plus': Plus,
  'repeat': ArrowsRepeat,
  'right-to-bracket': ArrowRightToBracket,
  'rotate': Refresh,
  'rotate-right': Refresh,
  'satellite-dish': Tracking,
  'save': FloppyDisk,
  'shield-alt': Shield,
  'shield-halved': Shield,
  'signal': Tracking,
  'sign-out-alt': OpenDoor,
  'sun': Sun,
  'tachometer-alt': Chart,
  'tags': Tag,
  'times': Close,
  'toolbox': Tools,
  'tower-broadcast': Server,
  'trash': TrashBin,
  'triangle-exclamation': ExclamationCircle,
  'upload': Upload,
  'user': User,
  'user-friends': UsersGroup,
  'users': Users,
  'user-tag': ProfileCard,
  'video': VideoCamera,
  'volume-high': VolumeUp,
  'wave-square': ChartLineUp,
}

export function Icon({
  name,
  className,
  ...props
}: Omit<SVGProps<SVGSVGElement>, 'name'> & { name: string }) {
  const Component = icons[name] ?? ExclamationCircle

  return (
    <Component
      aria-hidden={props['aria-label'] ? undefined : true}
      className={cn('inline-block size-[1em] shrink-0', className)}
      {...props}
    />
  )
}
